name: CI lmao

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
      
    - name: Setup everyshit and build game
      run: |
        echo "y" | haxelib setup -e
        echo "y" | haxelib install flixel
        echo "y" | haxelib install openfl
        echo "y" | haxelib install lime
        haxelib run lime setup
        haxelib run lime setup android
        haxelib run lime build android

    - name: Run tests
      run: haxelib run lime test android
      
    - name: Upload game artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Game
        path: .
