name: CI lmao

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
    
    - name: Install all dependencies
      run: |
        haxelib install lime
        haxelib install flixel
        haxelib install openfl
        
    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O android-sdk.zip
        unzip -q android-sdk.zip -d android-sdk
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        sdkmanager "build-tools;30.0.3" "platforms;android-30"
        
    - name: Setup lime and build game
      run: |
        lime config android
        lime build android

    - name: Run tests
      run: haxelib run lime test android
      
    - name: Upload game artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Game
        path: .
