name: CI lmao

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
      
    - name: Install dependencies
      run: |
        haxelib install lime
        haxelib install flixel
        haxelib install openfl
      
    - name: Setup everyshit
      run: |
        haxelib run lime setup
        echo "y" | lime config ANDROID_SETUP true
        
    - name: Build and test shits
      run: |
        echo "y" | lime build android --app-version="4.0.0-${{ github.run_id}}"
        lime test android
        
    - name: Upload game artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Game
        path: .
