name: CI lmao

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
    
    - name: Install some dependencies
      run: |
        haxelib install flixel
        haxelib install openfl
        
    - name: Setup Haxelib...
      run: echo "y" | haxelib setup -e
        
    - name: Setup lime and build game
      run: |
        haxelib install lime
        haxelib run lime setup
        haxelib run lime build android

    - name: Run tests
      run: haxelib run lime test android
      
    - name: Upload game artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Game
        path: .
