name: CI lol

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
    
    - name: Install all dependencies
      run: |
        haxelib install lime 8.0.2
        haxelib install flixel
        haxelib install openfl
        
    - name: Setup lime and build game
      run: |
        lime setup android
        haxelib run lime build android -Dci

    - name: Run tests
      run: haxelib run lime test android
      
    - name: Upload game artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Game
        path: .
