name: CI lmao

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1
      
    - name: Install dependencies
      run: |
        echo "{}" > haxelib.json
        haxelib install --always haxelib.json
      working-directory: .
      
    - name: Setup everyshit and build game
      run: |
        haxelib run lime setup
        haxelib run lime setup android
        haxelib run lime build android -debug

    - name: Run tests
      run: haxelib run lime test android
      
    - name: Upload game artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Game
        path: ./debug.apk
