name: CI lmao

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Haxe
      uses: krdlab/setup-haxe@v1.5.1
      
    - name: Install dependencies
      run: |
        haxelib install lime
        haxelib install flixel
        haxelib install openfl
      
    - name: Setup and build this shitty game
      # lime, im trying to build my shitty game and you ignoring some lines?
      # can someone explain?
      run: |
        haxelib run lime setup
        lime config ANDROID_SETUP true --non-interactive
        lime build android --app-version="4.0.0-${{ github.run_id }}" --non-interactive
        lime test android --non-interactive
        
    - name: Upload game artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Game
        path: .
    
  build-windows:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set Up Haxe
      uses: krdlab/setup-haxe@v1.5.1
      
    - name: Install dependencies
      run: |
        haxelib install lime
        haxelib install flixel
        haxelib install openfl
        
    - name: Setup and build this shitty game
      # im tired
      # bottom text
      run: |
        lime setup windows
        lime build windows
        
    - name: Upload game artifacts
      uses: actions/upload-artifacts@v3
      with:
        name: Game
        path: .